version: 2

sources:
  - name: staging
    description: This is a replica of the Postgres database used by our app.
    database: jaffle_shop  # Update this to match your warehouse database (e.g., dbt-tutorial, raw_data)
    schema: staging
    tables:
      - name: customers
        description: One record per customer.
      - name: items
        description: One record per order. Includes cancelled and deleted orders.
      - name: orders
        description: One record per customer.
      - name: products
        description: One record per order. Includes cancelled and deleted orders.
      - name: stores
        description: One record per customer.
      - name: supplies
        description: One record per order. Includes cancelled and deleted orders.
